// THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT

{% for dest in defs.destinations %}
#[doc = "{{ dest.description }}"]
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct {{ dest.name|struct_name }} {}
impl crate::Destination for {{ dest.name|struct_name }} {
    const ID: u8 = {{ dest.id }};
    const NAME: &'static str = "{{ dest.name }}";
    type Types = {{ dest.name }}::Types;
}

pub mod {{ dest.name }} {
    use crate::{Destination, Header, Type};
    use color_eyre::eyre::eyre;
    use std::io::{Read, Write};

    {% for ty in dest.types -%}
    #[derive(Clone, PartialEq, Eq)]
    pub struct {{ ty.name|struct_name }} {
        {% for field in ty.payload -%}
        pub {{ field.name }}: {{ field.ty() }},
    {% endfor %}{# field in ty.payload -#}
    }

    impl crate::Type for {{ ty.name|struct_name }} {
        const ID: u8 = {{ ty.id }};
        const NAME: &str = "{{ ty.name }}";
        const REPLY_TO: Option<&str> = {{ ty.reply_to() }};
    }

    impl crate::SerDe for {{ ty.name|struct_name }} {
        fn serialise(&self, buf: &mut [u8]) -> crate::Result<usize> {
            let mut cur = std::io::Cursor::new(buf);

            {% for field in ty.payload -%}
            cur.write_all({{ field.serialise_fn("self") }})?;
            {%- endfor %}{# field in ty.payload #}

            Ok(cur.position().try_into()?)
        }

        fn deserialise(buf: &[u8]) -> crate::Result<Self> {
            let mut cur = std::io::Cursor::new(buf);

            {% for field in ty.payload -%}
            {{ field.deserialise_fn("cur", 3) }}
            {%- endfor %}{# field in ty.payload #}

            Ok(Self {
                {% for field in ty.payload -%}
                {{ field.name }},
            {% endfor %}{# field in ty.payload -#}
            })
        }
    }

    impl std::fmt::Debug for {{ ty.name|struct_name }} {
        fn fmt(&self, fmt: &mut std::fmt::Formatter) -> std::fmt::Result {
            fmt.debug_struct("{{ ty.name|struct_name }}")
            {% for field in ty.payload -%}
                {% if field.is_slice() %}
                .field(
                    "{{ field.name }}",
                    &format_args!("{}",
                        crate::build_lib::hex_string_as_words(
                            &self.{{ field.name }},
                        ),
                    ),
                )
                {% else %}
                .field("{{ field.name }}", &format_args!("{:02x}", self.{{ field.name }}))
                {% endif %}{# field.is_slice() #}
            {%- endfor %}{# field in ty.payload #}
                .finish()
        }
    }
    {%- endfor %}{# ty in destination.types #}

    #[derive(Clone, Debug, PartialEq, Eq)]
    pub enum Types {
        {% for ty in dest.types -%}
        {{ ty.name|struct_name }}({{ ty.name|struct_name }}),
    {% endfor -%}{# ty in destination.types -#}
    }

    impl Types {
        pub const fn id(&self) -> u8 {
            match self {
                {% for ty in dest.types -%}
                Self::{{ ty.name|struct_name }}(_) => {{ ty.name|struct_name }}::ID,
            {% endfor -%}{# ty in destination.types -#}
            }
        }
    }

    impl crate::SerDe for Types {
        fn serialise(&self, buf: &mut [u8]) -> crate::Result<usize> {
            // skip header, then write full payload, then go back and
            // write header with correct length

            if buf.len() < 8 {
                return Err(eyre!("Buffer too short"));
            }

            let written_len = match self {
                {% for ty in dest.types -%}
                Self::{{ ty.name|struct_name }}(inner) =>
                    inner.serialise(&mut buf[4..])?,
            {% endfor -%}{# ty in destination.types -#}
            };

            let header = Header {
                destination: super::{{ dest.name|struct_name }}::ID,
                ty: self.id(),
                len: written_len.try_into()?,
            };
            buf[..4].copy_from_slice(&<[u8; 4]>::from(header));

            Ok(written_len+4)
        }

        fn deserialise(buf: &[u8]) -> crate::Result<Self> {
            if buf.len() < 8 {
                return Err(eyre!("Buffer too short"));
            }

            let header: [u8; 4] = buf[..4].try_into().unwrap();
            let header = Header::from(header);

            if buf.len()  < usize::from(header.len) + 4 {
                return Err(eyre!("Buffer too short"));
            }

            match header.ty {
                {% for ty in dest.types -%}
                {{ ty.id }} => {
                    let inner = {{ ty.name|struct_name }}::deserialise(&buf[4..])?;
                    Ok(Self::{{ ty.name|struct_name }}(inner))
                }
                {% endfor -%}{# ty in destination.types -#}
                other => Err(eyre!("Invalid type `{other:02x}")),
            }
        }
    }


    {% for ty in dest.types -%}
    impl From<{{ ty.name|struct_name }}> for Types {
        fn from(inner: {{ ty.name|struct_name }}) -> Self {
            Self::{{ ty.name|struct_name }}(inner)
        }
    }

    impl PartialEq<{{ ty.name|struct_name }}> for Types {
        fn eq(&self, rhs: &{{ ty.name|struct_name }}) -> bool {
            if let Self::{{ ty.name|struct_name }}(inner) = &self {
                inner == rhs
            } else {
                false
            }
        }
    }
{% endfor -%}{# ty in destination.types #}
}

{% endfor %}{# dest in defs.destinations #}
