[workspace]
members = [
	"2015/04",
	"2015/07",
	"2015/08",
	"2019/10",
	"2019/intcode_computer",
	"2020/*",
	"2021/*",
	"2022/*",
	"2023/*",
]
resolver = "2"

[profile.release]
overflow-checks = true
debug = true
opt-level = 3 # sometimes 's' might help
# panic = "abort"
