[package]
name = "types"
version = "0.1.0"
edition.workspace = true

[dependencies]
askama = "0.14.0"
color-eyre = "0.6.5"
hex = "0.4.3"
serde = { version = "1.0.228", features = ["derive"] }
serde_norway = "0.9.42"

[dev-dependencies]
hex-literal = "1.1.0"
insta = "1.45.0"
pretty_assertions = "1.4.1"

[build-dependencies]
askama = "0.14.0"
hex = "0.4.3"
serde = { version = "1.0.228", features = ["derive"] }
serde_norway = "0.9.42"
