-- THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT --

library ieee;
  use ieee.std_logic_1164.all;
  use ieee.numeric_std.all;

package packet_types_pkg_hdr is

  type t_packet_header is record
    DESTINATION : std_logic_vector(7 downto 0);
    TY          : std_logic_vector(7 downto 0);
    LENGTH      : std_logic_vector(15 downto 0);
  end record T_PACKET_HEADER;

  constant c_packet_header_init : T_PACKET_HEADER :=
  (
    DESTINATION => x"00",
    TY          => x"00",
    LENGTH      => x"0000"
  );

  constant c_num_destinations : natural := 1;

  -- Top-level packets, e.g. ping/pong
  constant c_destination_top                    : unsigned(7 downto 0) := x"00";
  constant c_destination_top_type_ping          : unsigned(7 downto 0) := x"00";
  constant c_destination_top_type_pong          : unsigned(7 downto 0) := x"01";
  constant c_destination_top_type_write_ram     : unsigned(7 downto 0) := x"02";
  constant c_destination_top_type_write_ram_ack : unsigned(7 downto 0) := x"03";
  constant c_destination_top_type_read_ram      : unsigned(7 downto 0) := x"04";
  constant c_destination_top_type_read_ram_ack  : unsigned(7 downto 0) := x"05";
  constant c_destination_top_type_run_day       : unsigned(7 downto 0) := x"06";
  constant c_destination_top_type_run_day_ack   : unsigned(7 downto 0) := x"07";

end package packet_types_pkg_hdr;
