[package]
name = "mining"
version = "0.1.0"
authors = ["David Young <david.young@nccgroup.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "1.2.1"
md-5 = "0.8"
