-- THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT --

library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

PACKAGE packet_types_pkg_hdr is
    TYPE T_PACKET_HEADER IS RECORD
        DESTINATION : std_logic_vector(7 downto 0);
        TY          : std_logic_vector(7 downto 0);
        LENGTH      : std_logic_vector(15 downto 0);
    END RECORD T_PACKET_HEADER;

    constant C_PACKET_HEADER_INIT: T_PACKET_HEADER := (
        DESTINATION => x"00",
        TY          => x"00",
        LENGTH      => x"0000"
    );

    constant C_NUM_DESTINATIONS: natural := 1;

    -- Top-level packets, e.g. ping/pong
    constant C_DESTINATION_top: unsigned(7 downto 0) := x"00";
    constant C_DESTINATION_top_TYPE_ping: unsigned(7 downto 0) := x"00";
END PACKAGE packet_types_pkg_hdr;
