use super::{Destination, Indent, Type};
use std::io::Write;

const HEADER: &str = "\
-- THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT --

library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
";
pub const MAIN_TYPES: &str = r#"
    TYPE T_PACKET_HEADER IS RECORD
        DESTINATION : std_logic_vector(7 downto 0);
        TY          : std_logic_vector(7 downto 0);
        LENGTH      : std_logic_vector(15 downto 0);
    END RECORD T_PACKET_HEADER;

    constant C_PACKET_HEADER_INIT: T_PACKET_HEADER := (
        DESTINATION => x"00",
        TY          => x"00",
        LENGTH      => x"0000"
    );
"#;
// const SLV: &str = "std_logic_vector(7 downto 0)";

pub fn write_header<W>(codegen: &mut W) -> std::io::Result<()>
where
    W: Write,
{
    writeln!(codegen, "{HEADER}")
}

pub fn write_destination<W>(
    codegen: &mut W,
    Destination {
        id,
        name,
        description,
        types: _,
    }: &Destination,
    indent: Indent,
) -> std::io::Result<()>
where
    W: Write,
{
    writeln!(codegen, "{indent}-- {description}")?;
    writeln!(
        codegen,
        "{indent}constant C_DESTINATION_{name}: natural := {id};",
    )
}

pub fn write_types<W>(
    codegen: &mut W,
    Destination {
        id: _,
        name: destination_name,
        description: _,
        types,
    }: &Destination,
    indent: Indent,
) -> std::io::Result<()>
where
    W: Write,
{
    for Type {
        id,
        name,
        reply_to: _,
        payload: _,
    } in types
    {
        writeln!(
            codegen,
            "{indent}constant C_DESTINATION_{destination_name}_TYPE_{name}: \
                natural := {id};",
        )?;
    }
    Ok(())
}
